apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: K8s-Dark-Cluster
spec:
  hosts:
  - ssh:
      address: 3.134.92.12
      user: ec2-user
      port: 22
      keyPath: 'C:\Users\rafae\.aws\KeyPairForEC2TestingInstances.pem'
    role: controller
  - ssh:
      address: 18.223.162.156
      user: ec2-user
      port: 22
      keyPath: 'C:\Users\rafae\.aws\KeyPairForEC2TestingInstances.pem'
    role: worker
  - ssh:
      address: 18.188.175.118
      user: ec2-user
      port: 22
      keyPath: 'C:\Users\rafae\.aws\KeyPairForEC2TestingInstances.pem'
    role: worker
  k0s:
    version: 1.23.1+k0s.1
